Document: debrepos
Title: Debian debrepos Manual
Author: <insert document author here>
Abstract: This manual describes what debrepos is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/debrepos/debrepos.sgml.gz

Format: postscript
Files: /usr/share/doc/debrepos/debrepos.ps.gz

Format: text
Files: /usr/share/doc/debrepos/debrepos.text.gz

Format: HTML
Index: /usr/share/doc/debrepos/html/index.html
Files: /usr/share/doc/debrepos/html/*.html
