#!/usr/bin/env python
import os, sys

from debrepos.main import MainManager

from optparse import OptionParser

# there is no use for the option parser now
parser = OptionParser()

parser.add_option('-v', '--verbose', action='store_true', dest='verbose',
                  default=False)


opts, args = parser.parse_args(sys.argv[1:])

def main(opts, args):
    manager = MainManager()

    if len(args) != 2:
        raise RuntimeError, "Wrong number of arguments - dist file.dsc"
    dist = args[0]
    dscfile = args[1]
    manager.install_to_repos(dist, dscfile)
    
if __name__ == "__main__":
    main(opts, args)

